// Code generated by protoc-gen-go.
// source: github.com/micro/slack-srv/proto/auth/auth.proto
// DO NOT EDIT!

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/auth/auth.proto

It has these top-level messages:
	TestRequest
	TestResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TestRequest struct {
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TestResponse struct {
	Ok     bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Team   string `protobuf:"bytes,3,opt,name=team" json:"team,omitempty"`
	User   string `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	TeamId string `protobuf:"bytes,5,opt,name=team_id" json:"team_id,omitempty"`
	UserId string `protobuf:"bytes,6,opt,name=user_id" json:"user_id,omitempty"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*TestRequest)(nil), "TestRequest")
	proto.RegisterType((*TestResponse)(nil), "TestResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthClient interface {
	Test(ctx context.Context, in *TestRequest) (*TestResponse, error)
}

type authClient struct {
	c client.Client
}

func NewAuthClient(c client.Client) AuthClient {
	if c == nil {
		c = client.NewClient()
	}
	return &authClient{
		c: c,
	}
}

func (c *authClient) Test(ctx context.Context, in *TestRequest) (*TestResponse, error) {
	req := c.c.NewRequest("auth", "Auth.Test", in)
	out := new(TestResponse)
	err := c.c.Call(ctx, req, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Test(context.Context, *TestRequest, *TestResponse) error
}

func RegisterAuthServer(s server.Server, srv AuthServer) {
	s.Handle(s.NewHandler(srv))
}

var fileDescriptor0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8e, 0x4f, 0x0b, 0x82, 0x30,
	0x18, 0x87, 0x53, 0x97, 0xd5, 0xab, 0x12, 0xec, 0x34, 0x3a, 0x85, 0x10, 0x74, 0x71, 0x8b, 0xfa,
	0x04, 0x7d, 0x85, 0xe8, 0x1e, 0x6a, 0x23, 0x45, 0x6d, 0xb6, 0x3f, 0x7d, 0xfe, 0xb6, 0x85, 0xe0,
	0x65, 0xe3, 0x79, 0x7e, 0x87, 0xf7, 0x81, 0xd3, 0xab, 0xd5, 0x8d, 0xa9, 0x68, 0x2d, 0x06, 0x36,
	0xb4, 0xb5, 0x14, 0x4c, 0xf5, 0x65, 0xdd, 0x15, 0x4a, 0x7e, 0xd9, 0x28, 0x85, 0x16, 0xac, 0x34,
	0xba, 0xf1, 0x0f, 0xf5, 0x9c, 0x67, 0x90, 0xdc, 0xb9, 0xd2, 0x37, 0xfe, 0x31, 0xf6, 0xcb, 0x39,
	0xa4, 0x7f, 0x54, 0xa3, 0x78, 0x2b, 0x8e, 0x01, 0x42, 0xd1, 0x91, 0x60, 0x1f, 0x1c, 0xd7, 0x38,
	0x81, 0xc8, 0xc8, 0x9e, 0x84, 0x16, 0x36, 0x38, 0x05, 0xa4, 0x79, 0x39, 0x90, 0x68, 0x22, 0xa3,
	0xb8, 0x24, 0xc8, 0xd3, 0x16, 0x56, 0x6e, 0x7b, 0xb4, 0x4f, 0xb2, 0x9c, 0x84, 0x9b, 0x9d, 0x88,
	0x9d, 0x38, 0x17, 0x80, 0xae, 0xb6, 0x01, 0x1f, 0x00, 0xb9, 0x73, 0x38, 0xa5, 0xb3, 0x88, 0x5d,
	0x46, 0xe7, 0x0d, 0xf9, 0xa2, 0x8a, 0x7d, 0xeb, 0xe5, 0x17, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x75,
	0x05, 0xaa, 0xdf, 0x00, 0x00, 0x00,
}
