// Code generated by protoc-gen-go.
// source: github.com/micro/slack-srv/proto/users/users.proto
// DO NOT EDIT!

/*
Package go_micro_srv_slack_users is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/users/users.proto

It has these top-level messages:
	Profile
	User
	GetPresenceRequest
	GetPresenceResponse
	SetPresenceRequest
	SetPresenceResponse
	InfoRequest
	InfoResponse
	ListRequest
	ListResponse
*/
package go_micro_srv_slack_users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Profile struct {
	FirstName string `protobuf:"bytes,1,opt,name=first_name" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=last_name" json:"last_name,omitempty"`
	RealName  string `protobuf:"bytes,3,opt,name=real_name" json:"real_name,omitempty"`
	Email     string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Skype     string `protobuf:"bytes,5,opt,name=skype" json:"skype,omitempty"`
	Phone     string `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	Image_24  string `protobuf:"bytes,7,opt,name=image_24" json:"image_24,omitempty"`
	Image_32  string `protobuf:"bytes,8,opt,name=image_32" json:"image_32,omitempty"`
	Image_48  string `protobuf:"bytes,9,opt,name=image_48" json:"image_48,omitempty"`
	Image_72  string `protobuf:"bytes,10,opt,name=image_72" json:"image_72,omitempty"`
	Image_192 string `protobuf:"bytes,11,opt,name=image_192" json:"image_192,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type User struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Deleted  bool     `protobuf:"varint,3,opt,name=deleted" json:"deleted,omitempty"`
	Color    string   `protobuf:"bytes,4,opt,name=color" json:"color,omitempty"`
	Profile  *Profile `protobuf:"bytes,5,opt,name=profile" json:"profile,omitempty"`
	IsAdmin  bool     `protobuf:"varint,6,opt,name=is_admin" json:"is_admin,omitempty"`
	IsOwner  bool     `protobuf:"varint,7,opt,name=is_owner" json:"is_owner,omitempty"`
	Has_2Fa  bool     `protobuf:"varint,8,opt,name=has_2fa" json:"has_2fa,omitempty"`
	HasFiles bool     `protobuf:"varint,9,opt,name=has_files" json:"has_files,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type GetPresenceRequest struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetPresenceRequest) Reset()                    { *m = GetPresenceRequest{} }
func (m *GetPresenceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPresenceRequest) ProtoMessage()               {}
func (*GetPresenceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetPresenceResponse struct {
	Ok              bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error           string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Presence        string `protobuf:"bytes,3,opt,name=presence" json:"presence,omitempty"`
	Online          bool   `protobuf:"varint,4,opt,name=online" json:"online,omitempty"`
	AutoAway        bool   `protobuf:"varint,5,opt,name=auto_away" json:"auto_away,omitempty"`
	ManualAway      bool   `protobuf:"varint,6,opt,name=manual_away" json:"manual_away,omitempty"`
	ConnectionCount int64  `protobuf:"varint,7,opt,name=connection_count" json:"connection_count,omitempty"`
	LastActivity    int64  `protobuf:"varint,8,opt,name=last_activity" json:"last_activity,omitempty"`
}

func (m *GetPresenceResponse) Reset()                    { *m = GetPresenceResponse{} }
func (m *GetPresenceResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPresenceResponse) ProtoMessage()               {}
func (*GetPresenceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SetPresenceRequest struct {
	Presence string `protobuf:"bytes,1,opt,name=presence" json:"presence,omitempty"`
}

func (m *SetPresenceRequest) Reset()                    { *m = SetPresenceRequest{} }
func (m *SetPresenceRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPresenceRequest) ProtoMessage()               {}
func (*SetPresenceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SetPresenceResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *SetPresenceResponse) Reset()                    { *m = SetPresenceResponse{} }
func (m *SetPresenceResponse) String() string            { return proto.CompactTextString(m) }
func (*SetPresenceResponse) ProtoMessage()               {}
func (*SetPresenceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type InfoRequest struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type InfoResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	User  *User  `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InfoResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListRequest struct {
	Presence int64 `protobuf:"varint,1,opt,name=presence" json:"presence,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ListResponse struct {
	Ok      bool    `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error   string  `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Members []*User `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ListResponse) GetMembers() []*User {
	if m != nil {
		return m.Members
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "go.micro.srv.slack.users.Profile")
	proto.RegisterType((*User)(nil), "go.micro.srv.slack.users.User")
	proto.RegisterType((*GetPresenceRequest)(nil), "go.micro.srv.slack.users.GetPresenceRequest")
	proto.RegisterType((*GetPresenceResponse)(nil), "go.micro.srv.slack.users.GetPresenceResponse")
	proto.RegisterType((*SetPresenceRequest)(nil), "go.micro.srv.slack.users.SetPresenceRequest")
	proto.RegisterType((*SetPresenceResponse)(nil), "go.micro.srv.slack.users.SetPresenceResponse")
	proto.RegisterType((*InfoRequest)(nil), "go.micro.srv.slack.users.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "go.micro.srv.slack.users.InfoResponse")
	proto.RegisterType((*ListRequest)(nil), "go.micro.srv.slack.users.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.srv.slack.users.ListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Users service

type UsersClient interface {
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...client.CallOption) (*GetPresenceResponse, error)
	SetPresence(ctx context.Context, in *SetPresenceRequest, opts ...client.CallOption) (*SetPresenceResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type usersClient struct {
	c           client.Client
	serviceName string
}

func NewUsersClient(serviceName string, c client.Client) UsersClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.slack.users"
	}
	return &usersClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *usersClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...client.CallOption) (*GetPresenceResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Users.GetPresence", in)
	out := new(GetPresenceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) SetPresence(ctx context.Context, in *SetPresenceRequest, opts ...client.CallOption) (*SetPresenceResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Users.SetPresence", in)
	out := new(SetPresenceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Info", in)
	out := new(InfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Users.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersHandler interface {
	GetPresence(context.Context, *GetPresenceRequest, *GetPresenceResponse) error
	SetPresence(context.Context, *SetPresenceRequest, *SetPresenceResponse) error
	Info(context.Context, *InfoRequest, *InfoResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterUsersHandler(s server.Server, hdlr UsersHandler) {
	s.Handle(s.NewHandler(&Users{hdlr}))
}

type Users struct {
	UsersHandler
}

func (h *Users) GetPresence(ctx context.Context, in *GetPresenceRequest, out *GetPresenceResponse) error {
	return h.UsersHandler.GetPresence(ctx, in, out)
}

func (h *Users) SetPresence(ctx context.Context, in *SetPresenceRequest, out *SetPresenceResponse) error {
	return h.UsersHandler.SetPresence(ctx, in, out)
}

func (h *Users) Info(ctx context.Context, in *InfoRequest, out *InfoResponse) error {
	return h.UsersHandler.Info(ctx, in, out)
}

func (h *Users) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.UsersHandler.List(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0x9b, 0x3a, 0x4d, 0x9c, 0xe3, 0x74, 0xeb, 0x1c, 0x06, 0xa6, 0x83, 0xfd, 0x11, 0xac,
	0xec, 0xa2, 0x75, 0x36, 0xb7, 0xb0, 0xed, 0x09, 0xc6, 0x60, 0x17, 0x65, 0x61, 0x14, 0x76, 0x63,
	0x14, 0xe7, 0x24, 0x11, 0xb1, 0x25, 0x4f, 0x92, 0x5b, 0xf2, 0x20, 0x7b, 0x8a, 0xbd, 0xc2, 0xde,
	0x60, 0x2f, 0x35, 0x4b, 0xb6, 0xc1, 0xa1, 0x4d, 0xd3, 0xde, 0x84, 0xe8, 0xd3, 0x91, 0xce, 0xf7,
	0x3b, 0x9f, 0x30, 0x44, 0x0b, 0xa6, 0x97, 0xc5, 0x34, 0x4c, 0x44, 0x36, 0xce, 0x58, 0x22, 0xc5,
	0x58, 0xa5, 0x34, 0x59, 0x9d, 0x29, 0x79, 0x3d, 0xce, 0xa5, 0xd0, 0x62, 0x5c, 0x28, 0x94, 0xaa,
	0xfa, 0x0d, 0xad, 0xe2, 0x07, 0x0b, 0x11, 0xda, 0xda, 0xb0, 0xac, 0x0a, 0x6d, 0x7d, 0x68, 0xf7,
	0xc9, 0xbf, 0x0e, 0xf4, 0x2f, 0xa5, 0x98, 0xb3, 0x14, 0x7d, 0x1f, 0x60, 0xce, 0xa4, 0xd2, 0x31,
	0xa7, 0x19, 0x06, 0x9d, 0xd7, 0x9d, 0x77, 0x03, 0xff, 0x19, 0x0c, 0x52, 0xda, 0x48, 0xfb, 0x8d,
	0x24, 0x91, 0xa6, 0x95, 0xe4, 0x58, 0xe9, 0x10, 0x0e, 0x30, 0xa3, 0x2c, 0x0d, 0xba, 0xcd, 0x52,
	0xad, 0xd6, 0x39, 0x06, 0x07, 0xcd, 0x32, 0x5f, 0x0a, 0x8e, 0x41, 0xcf, 0x2e, 0x8f, 0xc0, 0x65,
	0x19, 0x5d, 0x60, 0x1c, 0x5d, 0x04, 0xfd, 0x4d, 0xe5, 0x3c, 0x0a, 0xdc, 0x4d, 0xe5, 0xe2, 0x53,
	0x30, 0xd8, 0x54, 0x3e, 0x46, 0x01, 0x34, 0x3e, 0x2a, 0xe5, 0xc3, 0xe7, 0x28, 0xf0, 0x8c, 0x44,
	0xfe, 0x76, 0xa0, 0xfb, 0xa3, 0xe4, 0x2a, 0x49, 0xf6, 0xd9, 0xac, 0x46, 0x18, 0x42, 0xb7, 0xe5,
	0xfe, 0x29, 0xf4, 0x67, 0x98, 0xa2, 0xc6, 0x99, 0xf5, 0xee, 0x1a, 0x77, 0x89, 0x48, 0x85, 0xac,
	0xbd, 0x47, 0xd0, 0xcf, 0xab, 0x79, 0x58, 0xf7, 0x5e, 0xf4, 0x26, 0xdc, 0x36, 0xbc, 0xb0, 0x19,
	0x9c, 0xf1, 0xa6, 0x62, 0x3a, 0xcb, 0x18, 0xb7, 0x8c, 0x6e, 0xad, 0x88, 0x1b, 0x8e, 0xd2, 0x32,
	0xba, 0xa6, 0xef, 0x92, 0xaa, 0x38, 0x9a, 0x53, 0x8b, 0xe8, 0x1a, 0xfb, 0x46, 0x30, 0x17, 0x28,
	0xcb, 0xe8, 0x12, 0x02, 0xfe, 0x17, 0xd4, 0x97, 0x12, 0x15, 0xf2, 0x04, 0xbf, 0xe3, 0xaf, 0x02,
	0x95, 0x36, 0xfe, 0x4d, 0xbb, 0x8a, 0x86, 0xfc, 0xe9, 0xc0, 0x68, 0xa3, 0x48, 0xe5, 0x82, 0x2b,
	0x34, 0xc4, 0x62, 0x65, 0x6b, 0x2c, 0x12, 0x4a, 0x59, 0x22, 0xed, 0x37, 0xa3, 0xcb, 0xeb, 0xf2,
	0x3a, 0xaf, 0x27, 0xd0, 0x13, 0x3c, 0x65, 0x65, 0x24, 0xdd, 0xc6, 0x0b, 0x2d, 0xb4, 0x88, 0xe9,
	0x0d, 0x5d, 0x5b, 0x6c, 0xd7, 0x1f, 0x81, 0x97, 0x51, 0x5e, 0x94, 0x39, 0x5b, 0xb1, 0xc2, 0x0a,
	0xe0, 0x28, 0x11, 0x9c, 0x63, 0xa2, 0x99, 0xe0, 0x71, 0x22, 0x0a, 0xae, 0x2d, 0x9e, 0xe3, 0x3f,
	0x87, 0x43, 0xfb, 0x4e, 0x68, 0xb9, 0x75, 0xcd, 0xf4, 0xda, 0x42, 0x3a, 0xe4, 0x04, 0xfc, 0xc9,
	0x6d, 0xa2, 0xb6, 0xa1, 0x8a, 0xea, 0x3d, 0x8c, 0x26, 0x8f, 0x82, 0x22, 0x2f, 0xc0, 0xfb, 0xca,
	0xe7, 0xe2, 0xee, 0x21, 0x5d, 0xc1, 0xb0, 0xda, 0xdc, 0x3d, 0x9c, 0xd3, 0xfa, 0xa0, 0x63, 0xc3,
	0x7e, 0xb9, 0x3d, 0x6c, 0xf3, 0xae, 0xc8, 0x2b, 0xf0, 0xbe, 0x31, 0xa5, 0xb7, 0x81, 0x38, 0xe4,
	0x27, 0x0c, 0xab, 0x82, 0xdd, 0x9d, 0xc7, 0xd0, 0xcf, 0x30, 0x9b, 0x96, 0x77, 0x97, 0xcd, 0x9d,
	0xdd, 0xcd, 0xa3, 0xdf, 0x0e, 0x1c, 0x98, 0x3f, 0xca, 0x4f, 0xc1, 0x6b, 0xbd, 0x01, 0xff, 0x74,
	0xfb, 0xc1, 0xdb, 0xef, 0xe9, 0xf8, 0xec, 0x81, 0xd5, 0x15, 0x01, 0xd9, 0x33, 0xdd, 0x26, 0x0f,
	0xeb, 0x36, 0x79, 0x54, 0xb7, 0xc9, 0x9d, 0xdd, 0xae, 0xa0, 0x6b, 0xb2, 0xf3, 0xdf, 0x6e, 0x3f,
	0xd8, 0x0a, 0xfe, 0xf8, 0x64, 0x57, 0x59, 0xfb, 0x62, 0x13, 0xcd, 0x7d, 0x17, 0xb7, 0xb2, 0xbd,
	0xef, 0xe2, 0x76, 0xc2, 0x64, 0x6f, 0xda, 0xb3, 0x1f, 0xd9, 0xf3, 0xff, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x81, 0x44, 0x2f, 0x33, 0x9a, 0x05, 0x00, 0x00,
}
