// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/slack-srv/proto/team/team.proto

/*
Package go_micro_srv_slack_team is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/team/team.proto

It has these top-level messages:
	Icon
	TeamInfo
	InfoRequest
	InfoResponse
*/
package go_micro_srv_slack_team

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Team service

type TeamService interface {
	Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error)
}

type teamService struct {
	c           client.Client
	serviceName string
}

func TeamServiceClient(serviceName string, c client.Client) TeamService {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.slack.team"
	}
	return &teamService{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *teamService) Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Team.Info", in)
	out := new(InfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Team service

type TeamHandler interface {
	Info(context.Context, *InfoRequest, *InfoResponse) error
}

func RegisterTeamHandler(s server.Server, hdlr TeamHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Team{hdlr}, opts...))
}

type Team struct {
	TeamHandler
}

func (h *Team) Info(ctx context.Context, in *InfoRequest, out *InfoResponse) error {
	return h.TeamHandler.Info(ctx, in, out)
}
