// Code generated by protoc-gen-go.
// source: github.com/micro/slack-srv/proto/api/api.proto
// DO NOT EDIT!

/*
Package go_micro_srv_slack_api is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/api/api.proto

It has these top-level messages:
	TestRequest
	TestResponse
*/
package go_micro_srv_slack_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TestRequest struct {
	Error string            `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Args  map[string]string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestRequest) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type TestResponse struct {
	Ok    bool              `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Args  map[string]string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error string            `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TestResponse) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "go.micro.srv.slack.api.TestRequest")
	proto.RegisterType((*TestResponse)(nil), "go.micro.srv.slack.api.TestResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Api service

type ApiClient interface {
	Test(ctx context.Context, in *TestRequest) (*TestResponse, error)
}

type apiClient struct {
	c           client.Client
	serviceName string
}

func NewApiClient(serviceName string, c client.Client) ApiClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.slack.api"
	}
	return &apiClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *apiClient) Test(ctx context.Context, in *TestRequest) (*TestResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Api.Test", in)
	out := new(TestResponse)
	err := c.c.Call(ctx, req, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiHandler interface {
	Test(context.Context, *TestRequest, *TestResponse) error
}

func RegisterApiHandler(s server.Server, hdlr ApiHandler) {
	s.Handle(s.NewHandler(hdlr))
}

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xd2, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x2f, 0xce, 0x49,
	0x4c, 0xce, 0xd6, 0x2d, 0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0xc8,
	0x04, 0x61, 0x3d, 0x30, 0x4f, 0x48, 0x2c, 0x3d, 0x5f, 0x0f, 0xac, 0x4e, 0x0f, 0xa8, 0x42, 0x0f,
	0xac, 0x56, 0x0f, 0x28, 0xab, 0xd4, 0xc6, 0xc8, 0xc5, 0x1d, 0x92, 0x5a, 0x5c, 0x12, 0x94, 0x5a,
	0x58, 0x0a, 0xa4, 0x84, 0x78, 0xb9, 0x58, 0x53, 0x8b, 0x8a, 0xf2, 0x8b, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x85, 0xac, 0xb9, 0x58, 0x12, 0x8b, 0xd2, 0x8b, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8,
	0x8d, 0x74, 0xf5, 0xb0, 0x9b, 0xa2, 0x87, 0x64, 0x82, 0x9e, 0x23, 0x50, 0xbd, 0x6b, 0x5e, 0x49,
	0x51, 0xa5, 0x94, 0x36, 0x17, 0x27, 0x9c, 0x23, 0xc4, 0xcd, 0xc5, 0x9c, 0x9d, 0x5a, 0x09, 0x35,
	0x16, 0x68, 0x4b, 0x59, 0x62, 0x4e, 0x69, 0x2a, 0xd0, 0x5c, 0x20, 0xd7, 0x8a, 0xc9, 0x82, 0x51,
	0x69, 0x0a, 0x23, 0x17, 0x0f, 0xc4, 0x98, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x2e, 0x2e,
	0xa6, 0xfc, 0x6c, 0xb0, 0x7a, 0x0e, 0x21, 0x1b, 0x14, 0x67, 0xe8, 0xe1, 0x77, 0x06, 0x44, 0x3f,
	0xc2, 0x1d, 0x08, 0x3f, 0x31, 0x83, 0x6c, 0x23, 0xc9, 0x59, 0x46, 0x51, 0x5c, 0xcc, 0x8e, 0x05,
	0x99, 0x42, 0xc1, 0x5c, 0x2c, 0x20, 0xc3, 0x85, 0x94, 0x89, 0x08, 0x01, 0x29, 0x15, 0x62, 0xdc,
	0xa7, 0xc4, 0x90, 0xc4, 0x06, 0x8e, 0x1a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x83,
	0xde, 0xc5, 0xcc, 0x01, 0x00, 0x00,
}
