// Code generated by protoc-gen-go.
// source: github.com/micro/slack-srv/proto/api/api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/api/api.proto

It has these top-level messages:
	TestRequest
	TestResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TestRequest struct {
	Error string            `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Args  map[string]string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestRequest) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type TestResponse struct {
	Ok    bool              `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Args  map[string]string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error string            `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *TestResponse) Reset()                    { *m = TestResponse{} }
func (m *TestResponse) String() string            { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()               {}
func (*TestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TestResponse) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "TestRequest")
	proto.RegisterType((*TestResponse)(nil), "TestResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Api service

type ApiClient interface {
	Test(ctx context.Context, in *TestRequest) (*TestResponse, error)
}

type apiClient struct {
	c client.Client
}

func NewApiClient(c client.Client) ApiClient {
	if c == nil {
		c = client.NewClient()
	}
	return &apiClient{
		c: c,
	}
}

func (c *apiClient) Test(ctx context.Context, in *TestRequest) (*TestResponse, error) {
	req := c.c.NewRequest("api", "Api.Test", in)
	out := new(TestResponse)
	err := c.c.Call(ctx, req, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiServer interface {
	Test(context.Context, *TestRequest, *TestResponse) error
}

func RegisterApiServer(s server.Server, srv ApiServer) {
	s.Handle(s.NewHandler(srv))
}

var fileDescriptor0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xd2, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x2f, 0xce, 0x49,
	0x4c, 0xce, 0xd6, 0x2d, 0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x2c, 0xc8,
	0x04, 0x61, 0x3d, 0x30, 0x4f, 0x29, 0x9f, 0x8b, 0x3b, 0x24, 0xb5, 0xb8, 0x24, 0x28, 0xb5, 0xb0,
	0x14, 0x48, 0x09, 0xf1, 0x72, 0xb1, 0xa6, 0x16, 0x15, 0xe5, 0x17, 0x49, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x0a, 0xa9, 0x70, 0xb1, 0x24, 0x16, 0xa5, 0x17, 0x4b, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b,
	0x89, 0xe9, 0x21, 0x29, 0xd5, 0x73, 0x04, 0x4a, 0xb8, 0xe6, 0x95, 0x14, 0x55, 0x4a, 0x69, 0x73,
	0x71, 0xc2, 0x39, 0x42, 0xdc, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x50, 0xfd, 0x40, 0xe3, 0xca, 0x12,
	0x73, 0x4a, 0x53, 0x81, 0x06, 0x00, 0xb9, 0x56, 0x4c, 0x16, 0x8c, 0x4a, 0xb5, 0x5c, 0x3c, 0x10,
	0x53, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xb8, 0xb8, 0x98, 0xf2, 0xb3, 0xc1, 0xca, 0x39,
	0x84, 0x54, 0x51, 0xac, 0x13, 0xd7, 0x43, 0x56, 0x88, 0xb0, 0x0f, 0xe1, 0x48, 0x66, 0x90, 0xa9,
	0x24, 0x59, 0x6f, 0xa4, 0xc3, 0xc5, 0xec, 0x58, 0x90, 0x09, 0xb2, 0x09, 0x64, 0xb8, 0x10, 0x0f,
	0xb2, 0x97, 0xa4, 0x78, 0x51, 0x6c, 0x54, 0x62, 0x48, 0x62, 0x03, 0x07, 0x92, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xf5, 0xc7, 0xf1, 0x26, 0x56, 0x01, 0x00, 0x00,
}
