// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/slack-srv/proto/api/api.proto

/*
Package go_micro_srv_slack_api is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/api/api.proto

It has these top-level messages:
	TestRequest
	TestResponse
*/
package go_micro_srv_slack_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Api service

type ApiService interface {
	Test(ctx context.Context, in *TestRequest, opts ...client.CallOption) (*TestResponse, error)
}

type apiService struct {
	c           client.Client
	serviceName string
}

func ApiServiceClient(serviceName string, c client.Client) ApiService {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.slack.api"
	}
	return &apiService{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *apiService) Test(ctx context.Context, in *TestRequest, opts ...client.CallOption) (*TestResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Api.Test", in)
	out := new(TestResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Api service

type ApiHandler interface {
	Test(context.Context, *TestRequest, *TestResponse) error
}

func RegisterApiHandler(s server.Server, hdlr ApiHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Api{hdlr}, opts...))
}

type Api struct {
	ApiHandler
}

func (h *Api) Test(ctx context.Context, in *TestRequest, out *TestResponse) error {
	return h.ApiHandler.Test(ctx, in, out)
}
