// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/slack-srv/proto/common.proto

/*
Package go_micro_srv_slack is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/common.proto

It has these top-level messages:
	Message
	Topic
	Purpose
*/
package go_micro_srv_slack

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Type      string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Ts        string `protobuf:"bytes,2,opt,name=ts" json:"ts,omitempty"`
	User      string `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Text      string `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	IsStarred bool   `protobuf:"varint,5,opt,name=is_starred,json=isStarred" json:"is_starred,omitempty"`
	Wibblr    bool   `protobuf:"varint,6,opt,name=wibblr" json:"wibblr,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

func (m *Message) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetIsStarred() bool {
	if m != nil {
		return m.IsStarred
	}
	return false
}

func (m *Message) GetWibblr() bool {
	if m != nil {
		return m.Wibblr
	}
	return false
}

type Topic struct {
	Value   string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator" json:"creator,omitempty"`
	LastSet int64  `protobuf:"varint,3,opt,name=last_set,json=lastSet" json:"last_set,omitempty"`
}

func (m *Topic) Reset()                    { *m = Topic{} }
func (m *Topic) String() string            { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()               {}
func (*Topic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Topic) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Topic) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Topic) GetLastSet() int64 {
	if m != nil {
		return m.LastSet
	}
	return 0
}

type Purpose struct {
	Value   string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator" json:"creator,omitempty"`
	LastSet int64  `protobuf:"varint,3,opt,name=last_set,json=lastSet" json:"last_set,omitempty"`
}

func (m *Purpose) Reset()                    { *m = Purpose{} }
func (m *Purpose) String() string            { return proto.CompactTextString(m) }
func (*Purpose) ProtoMessage()               {}
func (*Purpose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Purpose) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Purpose) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Purpose) GetLastSet() int64 {
	if m != nil {
		return m.LastSet
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.slack.Message")
	proto.RegisterType((*Topic)(nil), "go.micro.srv.slack.Topic")
	proto.RegisterType((*Purpose)(nil), "go.micro.srv.slack.Purpose")
}

func init() { proto.RegisterFile("github.com/micro/slack-srv/proto/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x41, 0x6e, 0xab, 0x30,
	0x10, 0x86, 0x05, 0x09, 0x90, 0xcc, 0xe2, 0x2d, 0xac, 0xa7, 0xca, 0x5d, 0x54, 0x8a, 0x58, 0x65,
	0x13, 0xb3, 0xe8, 0x39, 0x2a, 0x55, 0x24, 0xfb, 0xc8, 0xb8, 0x23, 0x6a, 0x15, 0x6a, 0x34, 0x33,
	0xd0, 0xf4, 0x0e, 0x3d, 0x74, 0x85, 0x21, 0x37, 0xe8, 0x6e, 0xbe, 0xf1, 0xf7, 0x5b, 0xbf, 0x06,
	0x4e, 0xad, 0x97, 0xf7, 0xb1, 0x31, 0x2e, 0xf4, 0x55, 0xef, 0x1d, 0x85, 0x8a, 0x3b, 0xeb, 0x3e,
	0x4e, 0x4c, 0x53, 0x35, 0x50, 0x90, 0x50, 0xb9, 0xd0, 0xf7, 0xe1, 0xd3, 0x44, 0x50, 0xaa, 0x0d,
	0x26, 0x6a, 0x86, 0x69, 0x32, 0x51, 0x2d, 0x7f, 0x12, 0x28, 0x5e, 0x90, 0xd9, 0xb6, 0xa8, 0x14,
	0x6c, 0xe5, 0x7b, 0x40, 0x9d, 0x1c, 0x92, 0xe3, 0xbe, 0x8e, 0xb3, 0xfa, 0x07, 0xa9, 0xb0, 0x4e,
	0xe3, 0x26, 0x15, 0x9e, 0x9d, 0x91, 0x91, 0xf4, 0x66, 0x71, 0xe6, 0x39, 0xe6, 0xf0, 0x26, 0x7a,
	0xbb, 0xe6, 0xf0, 0x26, 0xea, 0x09, 0xc0, 0xf3, 0x95, 0xc5, 0x12, 0xe1, 0x9b, 0xce, 0x0e, 0xc9,
	0x71, 0x57, 0xef, 0x3d, 0x9f, 0x97, 0x85, 0x7a, 0x80, 0xfc, 0xcb, 0x37, 0x4d, 0x47, 0x3a, 0x8f,
	0x4f, 0x2b, 0x95, 0x35, 0x64, 0x97, 0x30, 0x78, 0xa7, 0xfe, 0x43, 0x36, 0xd9, 0x6e, 0xbc, 0x97,
	0x59, 0x40, 0x69, 0x28, 0x1c, 0xa1, 0x95, 0x40, 0x6b, 0xa5, 0x3b, 0xaa, 0x47, 0xd8, 0x75, 0x96,
	0xe5, 0xca, 0x28, 0xb1, 0xdb, 0xa6, 0x2e, 0x66, 0x3e, 0xa3, 0x94, 0x17, 0x28, 0x5e, 0x47, 0x1a,
	0x02, 0xe3, 0x1f, 0xfe, 0xda, 0xe4, 0xf1, 0xa6, 0xcf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4,
	0xd6, 0xad, 0xed, 0x84, 0x01, 0x00, 0x00,
}
