// Code generated by protoc-gen-go.
// source: github.com/micro/slack-srv/proto/channels/channels.proto
// DO NOT EDIT!

/*
Package go_micro_srv_slack is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/channels/channels.proto

It has these top-level messages:
	Channel
	Topic
	Purpose
	Message
	ListRequest
	ListResponse
	HistoryRequest
	HistoryResponse
	InfoRequest
	InfoResponse
	MarkRequest
	MarkResponse
	SetPurposeRequest
	SetPurposeResponse
	SetTopicRequest
	SetTopicResponse
*/
package go_micro_srv_slack

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Channel struct {
	Id                 string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name               string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Created            int64    `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Creator            string   `protobuf:"bytes,4,opt,name=creator" json:"creator,omitempty"`
	IsArchived         bool     `protobuf:"varint,5,opt,name=is_archived" json:"is_archived,omitempty"`
	IsMember           bool     `protobuf:"varint,6,opt,name=is_member" json:"is_member,omitempty"`
	IsGeneral          bool     `protobuf:"varint,7,opt,name=is_general" json:"is_general,omitempty"`
	NumMembers         int64    `protobuf:"varint,8,opt,name=num_members" json:"num_members,omitempty"`
	Topic              *Topic   `protobuf:"bytes,9,opt,name=topic" json:"topic,omitempty"`
	Purpose            *Purpose `protobuf:"bytes,10,opt,name=purpose" json:"purpose,omitempty"`
	Members            []string `protobuf:"bytes,11,rep,name=members" json:"members,omitempty"`
	LatestRead         string   `protobuf:"bytes,12,opt,name=latest_read" json:"latest_read,omitempty"`
	Latest             *Message `protobuf:"bytes,13,opt,name=latest" json:"latest,omitempty"`
	UnreadCount        int64    `protobuf:"varint,14,opt,name=unread_count" json:"unread_count,omitempty"`
	UnreadCountDisplay int64    `protobuf:"varint,15,opt,name=unread_count_display" json:"unread_count_display,omitempty"`
}

func (m *Channel) Reset()                    { *m = Channel{} }
func (m *Channel) String() string            { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()               {}
func (*Channel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Channel) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Channel) GetPurpose() *Purpose {
	if m != nil {
		return m.Purpose
	}
	return nil
}

func (m *Channel) GetLatest() *Message {
	if m != nil {
		return m.Latest
	}
	return nil
}

type Topic struct {
	Value   string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator" json:"creator,omitempty"`
	LastSet int64  `protobuf:"varint,3,opt,name=last_set" json:"last_set,omitempty"`
}

func (m *Topic) Reset()                    { *m = Topic{} }
func (m *Topic) String() string            { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()               {}
func (*Topic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Purpose struct {
	Value   string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator" json:"creator,omitempty"`
	LastSet int64  `protobuf:"varint,3,opt,name=last_set" json:"last_set,omitempty"`
}

func (m *Purpose) Reset()                    { *m = Purpose{} }
func (m *Purpose) String() string            { return proto.CompactTextString(m) }
func (*Purpose) ProtoMessage()               {}
func (*Purpose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Message struct {
	Type      string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Ts        string `protobuf:"bytes,2,opt,name=ts" json:"ts,omitempty"`
	User      string `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Text      string `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	IsStarred bool   `protobuf:"varint,5,opt,name=is_starred" json:"is_starred,omitempty"`
	Wibblr    bool   `protobuf:"varint,6,opt,name=wibblr" json:"wibblr,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListRequest struct {
	ExcludeArchived int64 `protobuf:"varint,1,opt,name=exclude_archived" json:"exclude_archived,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListResponse struct {
	Ok       bool       `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error    string     `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Channels []*Channel `protobuf:"bytes,3,rep,name=channels" json:"channels,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListResponse) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type HistoryRequest struct {
	Channel   string  `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Latest    float64 `protobuf:"fixed64,2,opt,name=latest" json:"latest,omitempty"`
	Oldest    float64 `protobuf:"fixed64,3,opt,name=oldest" json:"oldest,omitempty"`
	Inclusive int64   `protobuf:"varint,4,opt,name=inclusive" json:"inclusive,omitempty"`
	Count     int64   `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	Unreads   int64   `protobuf:"varint,6,opt,name=unreads" json:"unreads,omitempty"`
}

func (m *HistoryRequest) Reset()                    { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()               {}
func (*HistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type HistoryResponse struct {
	Ok       bool       `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Latest   string     `protobuf:"bytes,2,opt,name=latest" json:"latest,omitempty"`
	Messages []*Message `protobuf:"bytes,3,rep,name=messages" json:"messages,omitempty"`
	HasMore  bool       `protobuf:"varint,4,opt,name=has_more" json:"has_more,omitempty"`
}

func (m *HistoryResponse) Reset()                    { *m = HistoryResponse{} }
func (m *HistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*HistoryResponse) ProtoMessage()               {}
func (*HistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *HistoryResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type InfoRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type InfoResponse struct {
	Ok      bool     `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Channel *Channel `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *InfoResponse) GetChannel() *Channel {
	if m != nil {
		return m.Channel
	}
	return nil
}

type MarkRequest struct {
	Channel string  `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Ts      float64 `protobuf:"fixed64,2,opt,name=ts" json:"ts,omitempty"`
}

func (m *MarkRequest) Reset()                    { *m = MarkRequest{} }
func (m *MarkRequest) String() string            { return proto.CompactTextString(m) }
func (*MarkRequest) ProtoMessage()               {}
func (*MarkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type MarkResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *MarkResponse) Reset()                    { *m = MarkResponse{} }
func (m *MarkResponse) String() string            { return proto.CompactTextString(m) }
func (*MarkResponse) ProtoMessage()               {}
func (*MarkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type SetPurposeRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Purpose string `protobuf:"bytes,2,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *SetPurposeRequest) Reset()                    { *m = SetPurposeRequest{} }
func (m *SetPurposeRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPurposeRequest) ProtoMessage()               {}
func (*SetPurposeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type SetPurposeResponse struct {
	Ok      bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Purpose string `protobuf:"bytes,2,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *SetPurposeResponse) Reset()                    { *m = SetPurposeResponse{} }
func (m *SetPurposeResponse) String() string            { return proto.CompactTextString(m) }
func (*SetPurposeResponse) ProtoMessage()               {}
func (*SetPurposeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type SetTopicRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Topic   string `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
}

func (m *SetTopicRequest) Reset()                    { *m = SetTopicRequest{} }
func (m *SetTopicRequest) String() string            { return proto.CompactTextString(m) }
func (*SetTopicRequest) ProtoMessage()               {}
func (*SetTopicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type SetTopicResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Topic string `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
}

func (m *SetTopicResponse) Reset()                    { *m = SetTopicResponse{} }
func (m *SetTopicResponse) String() string            { return proto.CompactTextString(m) }
func (*SetTopicResponse) ProtoMessage()               {}
func (*SetTopicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func init() {
	proto.RegisterType((*Channel)(nil), "go.micro.srv.slack.Channel")
	proto.RegisterType((*Topic)(nil), "go.micro.srv.slack.Topic")
	proto.RegisterType((*Purpose)(nil), "go.micro.srv.slack.Purpose")
	proto.RegisterType((*Message)(nil), "go.micro.srv.slack.Message")
	proto.RegisterType((*ListRequest)(nil), "go.micro.srv.slack.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.srv.slack.ListResponse")
	proto.RegisterType((*HistoryRequest)(nil), "go.micro.srv.slack.HistoryRequest")
	proto.RegisterType((*HistoryResponse)(nil), "go.micro.srv.slack.HistoryResponse")
	proto.RegisterType((*InfoRequest)(nil), "go.micro.srv.slack.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "go.micro.srv.slack.InfoResponse")
	proto.RegisterType((*MarkRequest)(nil), "go.micro.srv.slack.MarkRequest")
	proto.RegisterType((*MarkResponse)(nil), "go.micro.srv.slack.MarkResponse")
	proto.RegisterType((*SetPurposeRequest)(nil), "go.micro.srv.slack.SetPurposeRequest")
	proto.RegisterType((*SetPurposeResponse)(nil), "go.micro.srv.slack.SetPurposeResponse")
	proto.RegisterType((*SetTopicRequest)(nil), "go.micro.srv.slack.SetTopicRequest")
	proto.RegisterType((*SetTopicResponse)(nil), "go.micro.srv.slack.SetTopicResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Channels service

type ChannelsClient interface {
	List(ctx context.Context, in *ListRequest) (*ListResponse, error)
}

type channelsClient struct {
	c client.Client
}

func NewChannelsClient(c client.Client) ChannelsClient {
	if c == nil {
		c = client.NewClient()
	}
	return &channelsClient{
		c: c,
	}
}

func (c *channelsClient) List(ctx context.Context, in *ListRequest) (*ListResponse, error) {
	req := c.c.NewRequest("go.micro.srv.slack", "Channels.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Channels service

type ChannelsServer interface {
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterChannelsServer(s server.Server, srv ChannelsServer) {
	s.Handle(s.NewHandler(srv))
}

var fileDescriptor0 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xa6, 0xcd, 0xda, 0x66, 0xaf, 0x5d, 0xbb, 0x85, 0x1d, 0xcc, 0x40, 0x30, 0xf9, 0xc2, 0x04,
	0x5b, 0x2a, 0x86, 0x90, 0x40, 0x1c, 0xb9, 0x0c, 0xc1, 0x24, 0x04, 0x48, 0x70, 0xab, 0xdc, 0xc4,
	0xb4, 0xd1, 0x92, 0x38, 0xd8, 0xce, 0xd8, 0x7e, 0x38, 0x77, 0x9e, 0xed, 0x24, 0x2d, 0x5a, 0x82,
	0xc4, 0xad, 0x7e, 0xfe, 0xbe, 0xbc, 0xef, 0x7b, 0xdf, 0x73, 0xe1, 0xf5, 0x2a, 0xd1, 0xeb, 0x72,
	0x19, 0x46, 0x22, 0x9b, 0x67, 0x49, 0x24, 0xc5, 0x5c, 0xa5, 0x2c, 0xba, 0x3a, 0x53, 0xf2, 0x7a,
	0x5e, 0x48, 0xa1, 0xc5, 0x3c, 0x5a, 0xb3, 0x3c, 0xe7, 0xa9, 0x6a, 0x7e, 0x84, 0xb6, 0x1e, 0x04,
	0x2b, 0x11, 0x5a, 0x46, 0x88, 0xd8, 0xd0, 0xb2, 0xe8, 0xef, 0x3e, 0x8c, 0xde, 0x39, 0x58, 0x00,
	0xd0, 0x4f, 0x62, 0xd2, 0x3b, 0xee, 0x9d, 0xec, 0x06, 0x13, 0xd8, 0xc9, 0x59, 0xc6, 0x49, 0xdf,
	0x9e, 0x66, 0x30, 0x8a, 0x24, 0x67, 0x9a, 0xc7, 0xc4, 0xc3, 0x82, 0xd7, 0x14, 0x84, 0x24, 0x3b,
	0x16, 0x71, 0x1f, 0xc6, 0x89, 0x5a, 0x30, 0x19, 0xad, 0x93, 0x6b, 0x44, 0x0d, 0xb0, 0xe8, 0x07,
	0x07, 0xb0, 0x8b, 0xc5, 0x8c, 0x67, 0x4b, 0x2e, 0xc9, 0xd0, 0x96, 0xb0, 0x09, 0x96, 0x56, 0x3c,
	0xe7, 0x92, 0xa5, 0x64, 0x64, 0x6b, 0xc8, 0xcd, 0xcb, 0xac, 0xc2, 0x29, 0xe2, 0xdb, 0x0e, 0x27,
	0x30, 0xd0, 0xa2, 0x48, 0x22, 0xb2, 0x8b, 0xc7, 0xf1, 0xf9, 0x83, 0xf0, 0xae, 0xf8, 0xf0, 0xab,
	0x01, 0x04, 0xa7, 0x30, 0x2a, 0x4a, 0x59, 0x08, 0xc5, 0x09, 0x58, 0xec, 0xc3, 0x36, 0xec, 0x27,
	0x07, 0x31, 0xca, 0xeb, 0x46, 0xe3, 0x63, 0xcf, 0x29, 0x4f, 0xd1, 0x99, 0xd2, 0x0b, 0x34, 0x14,
	0x93, 0x89, 0xb5, 0xf3, 0x1c, 0x86, 0xae, 0x48, 0xf6, 0xba, 0x3f, 0x79, 0xc9, 0x95, 0x62, 0x2b,
	0x1e, 0x1c, 0xc2, 0xa4, 0xcc, 0x0d, 0x79, 0x11, 0x89, 0x32, 0xd7, 0x64, 0x6a, 0x0d, 0x3c, 0x82,
	0xc3, 0xed, 0xea, 0x22, 0x4e, 0x54, 0x91, 0xb2, 0x5b, 0x32, 0x33, 0xb7, 0xf4, 0x0d, 0x0c, 0x9c,
	0xfa, 0x3d, 0x18, 0x5c, 0xb3, 0xb4, 0xe4, 0xd5, 0xdc, 0xb7, 0x06, 0xeb, 0x46, 0xbf, 0x0f, 0x7e,
	0xca, 0x50, 0x9c, 0xe2, 0xda, 0xcd, 0x9e, 0xbe, 0x85, 0x51, 0x6d, 0xe6, 0xff, 0xc9, 0x11, 0x8c,
	0x6a, 0xd9, 0x18, 0xb1, 0xbe, 0x2d, 0x6a, 0x2e, 0x86, 0xaf, 0x55, 0x45, 0xc3, 0x9b, 0x52, 0x61,
	0x64, 0x5e, 0x7d, 0xd2, 0xfc, 0x46, 0x57, 0x41, 0xbb, 0x00, 0x95, 0x66, 0x52, 0x36, 0x39, 0x4f,
	0x61, 0xf8, 0x2b, 0x59, 0x2e, 0xd3, 0x2a, 0x64, 0xfa, 0x14, 0xc6, 0x1f, 0x13, 0xa5, 0x3f, 0xf3,
	0x9f, 0x25, 0x8e, 0x30, 0x20, 0xb0, 0xcf, 0x6f, 0xa2, 0xb4, 0x8c, 0xf9, 0x66, 0x41, 0x7a, 0x56,
	0xcd, 0x77, 0x98, 0x38, 0xa0, 0x2a, 0x44, 0x8e, 0x7e, 0x50, 0x84, 0xb8, 0xb2, 0x77, 0xbe, 0xf1,
	0xc6, 0xa5, 0x6c, 0xac, 0x9c, 0x81, 0x5f, 0xaf, 0x33, 0xea, 0xf2, 0xba, 0x32, 0xa9, 0x76, 0x99,
	0x6a, 0x98, 0x5e, 0xe0, 0x97, 0x85, 0xbc, 0xad, 0x55, 0x98, 0xe1, 0xb8, 0xcb, 0xca, 0xf1, 0xb4,
	0xc9, 0xd8, 0x74, 0xe8, 0x99, 0xb3, 0x48, 0x63, 0x73, 0xf6, 0xec, 0xd9, 0x6c, 0x6f, 0x8e, 0xb2,
	0x15, 0x0a, 0xb6, 0xe6, 0x3d, 0xa3, 0xc9, 0x45, 0x3c, 0xa8, 0x5f, 0x81, 0x8b, 0x58, 0x59, 0xe3,
	0x1e, 0xcd, 0x61, 0xd6, 0x74, 0x6d, 0xb1, 0xf4, 0x77, 0x47, 0xeb, 0x29, 0x73, 0x61, 0xfc, 0xd3,
	0x53, 0x1d, 0x18, 0xa6, 0xb9, 0x66, 0xf8, 0x9e, 0x84, 0x74, 0x7a, 0x7c, 0xfa, 0x18, 0xc6, 0xef,
	0xf3, 0x1f, 0xa2, 0xcb, 0x22, 0xbd, 0x80, 0x89, 0xbb, 0x6f, 0x11, 0x73, 0xba, 0x01, 0xf7, 0xbb,
	0x77, 0xbc, 0x9e, 0xe7, 0x33, 0x18, 0x5f, 0x32, 0x79, 0xd5, 0x39, 0xcc, 0xcd, 0xfa, 0xf4, 0xe8,
	0x11, 0x4c, 0x1c, 0xf6, 0x6e, 0x57, 0xfa, 0x0a, 0x0e, 0xbe, 0x70, 0x5d, 0xed, 0x6f, 0xe7, 0xd7,
	0x66, 0x9b, 0x27, 0x6d, 0x27, 0x45, 0x5f, 0x40, 0xb0, 0x4d, 0x6b, 0xb1, 0xd3, 0x42, 0x99, 0x21,
	0xc5, 0x3e, 0xb2, 0xce, 0x3e, 0x7b, 0xf5, 0x9f, 0x8c, 0xa3, 0x9c, 0xc1, 0xfe, 0x86, 0xd2, 0xbe,
	0x92, 0x5b, 0xf0, 0xf3, 0x6f, 0xe0, 0x57, 0xe3, 0x51, 0xc1, 0x07, 0xd8, 0x31, 0x9b, 0x1c, 0x3c,
	0x69, 0x1b, 0xe2, 0xd6, 0x63, 0x38, 0x3a, 0xee, 0x06, 0xb8, 0x8e, 0xf4, 0xde, 0x72, 0x68, 0xff,
	0xaf, 0x5f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x5a, 0x0f, 0x0f, 0xeb, 0x05, 0x00, 0x00,
}
