// Code generated by protoc-gen-go.
// source: github.com/micro/slack-srv/proto/channels/channels.proto
// DO NOT EDIT!

/*
Package go_micro_srv_slack is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/channels/channels.proto

It has these top-level messages:
	Channel
	ListRequest
	ListResponse
	HistoryRequest
	HistoryResponse
	InfoRequest
	InfoResponse
	MarkRequest
	MarkResponse
	SetPurposeRequest
	SetPurposeResponse
	SetTopicRequest
	SetTopicResponse
*/
package go_micro_srv_slack

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_srv_slack1 "github.com/micro/slack-srv/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Channel struct {
	Id                 string                       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name               string                       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Created            int64                        `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Creator            string                       `protobuf:"bytes,4,opt,name=creator" json:"creator,omitempty"`
	IsArchived         bool                         `protobuf:"varint,5,opt,name=is_archived" json:"is_archived,omitempty"`
	IsMember           bool                         `protobuf:"varint,6,opt,name=is_member" json:"is_member,omitempty"`
	IsGeneral          bool                         `protobuf:"varint,7,opt,name=is_general" json:"is_general,omitempty"`
	NumMembers         int64                        `protobuf:"varint,8,opt,name=num_members" json:"num_members,omitempty"`
	Topic              *go_micro_srv_slack1.Topic   `protobuf:"bytes,9,opt,name=topic" json:"topic,omitempty"`
	Purpose            *go_micro_srv_slack1.Purpose `protobuf:"bytes,10,opt,name=purpose" json:"purpose,omitempty"`
	Members            []string                     `protobuf:"bytes,11,rep,name=members" json:"members,omitempty"`
	LatestRead         string                       `protobuf:"bytes,12,opt,name=latest_read" json:"latest_read,omitempty"`
	Latest             *go_micro_srv_slack1.Message `protobuf:"bytes,13,opt,name=latest" json:"latest,omitempty"`
	UnreadCount        int64                        `protobuf:"varint,14,opt,name=unread_count" json:"unread_count,omitempty"`
	UnreadCountDisplay int64                        `protobuf:"varint,15,opt,name=unread_count_display" json:"unread_count_display,omitempty"`
}

func (m *Channel) Reset()                    { *m = Channel{} }
func (m *Channel) String() string            { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()               {}
func (*Channel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Channel) GetTopic() *go_micro_srv_slack1.Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Channel) GetPurpose() *go_micro_srv_slack1.Purpose {
	if m != nil {
		return m.Purpose
	}
	return nil
}

func (m *Channel) GetLatest() *go_micro_srv_slack1.Message {
	if m != nil {
		return m.Latest
	}
	return nil
}

type ListRequest struct {
	ExcludeArchived int64 `protobuf:"varint,1,opt,name=exclude_archived" json:"exclude_archived,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListResponse struct {
	Ok       bool       `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error    string     `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Channels []*Channel `protobuf:"bytes,3,rep,name=channels" json:"channels,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListResponse) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type HistoryRequest struct {
	Channel   string  `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Latest    float64 `protobuf:"fixed64,2,opt,name=latest" json:"latest,omitempty"`
	Oldest    float64 `protobuf:"fixed64,3,opt,name=oldest" json:"oldest,omitempty"`
	Inclusive int64   `protobuf:"varint,4,opt,name=inclusive" json:"inclusive,omitempty"`
	Count     int64   `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	Unreads   int64   `protobuf:"varint,6,opt,name=unreads" json:"unreads,omitempty"`
}

func (m *HistoryRequest) Reset()                    { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()               {}
func (*HistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type HistoryResponse struct {
	Ok       bool                           `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error    string                         `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Latest   string                         `protobuf:"bytes,3,opt,name=latest" json:"latest,omitempty"`
	Messages []*go_micro_srv_slack1.Message `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`
	HasMore  bool                           `protobuf:"varint,5,opt,name=has_more" json:"has_more,omitempty"`
}

func (m *HistoryResponse) Reset()                    { *m = HistoryResponse{} }
func (m *HistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*HistoryResponse) ProtoMessage()               {}
func (*HistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HistoryResponse) GetMessages() []*go_micro_srv_slack1.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type InfoRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type InfoResponse struct {
	Ok      bool     `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error   string   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Channel *Channel `protobuf:"bytes,3,opt,name=channel" json:"channel,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InfoResponse) GetChannel() *Channel {
	if m != nil {
		return m.Channel
	}
	return nil
}

type MarkRequest struct {
	Channel string  `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Ts      float64 `protobuf:"fixed64,2,opt,name=ts" json:"ts,omitempty"`
}

func (m *MarkRequest) Reset()                    { *m = MarkRequest{} }
func (m *MarkRequest) String() string            { return proto.CompactTextString(m) }
func (*MarkRequest) ProtoMessage()               {}
func (*MarkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type MarkResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *MarkResponse) Reset()                    { *m = MarkResponse{} }
func (m *MarkResponse) String() string            { return proto.CompactTextString(m) }
func (*MarkResponse) ProtoMessage()               {}
func (*MarkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SetPurposeRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Purpose string `protobuf:"bytes,2,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *SetPurposeRequest) Reset()                    { *m = SetPurposeRequest{} }
func (m *SetPurposeRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPurposeRequest) ProtoMessage()               {}
func (*SetPurposeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SetPurposeResponse struct {
	Ok      bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Purpose string `protobuf:"bytes,3,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *SetPurposeResponse) Reset()                    { *m = SetPurposeResponse{} }
func (m *SetPurposeResponse) String() string            { return proto.CompactTextString(m) }
func (*SetPurposeResponse) ProtoMessage()               {}
func (*SetPurposeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SetTopicRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Topic   string `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
}

func (m *SetTopicRequest) Reset()                    { *m = SetTopicRequest{} }
func (m *SetTopicRequest) String() string            { return proto.CompactTextString(m) }
func (*SetTopicRequest) ProtoMessage()               {}
func (*SetTopicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type SetTopicResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Topic string `protobuf:"bytes,3,opt,name=topic" json:"topic,omitempty"`
}

func (m *SetTopicResponse) Reset()                    { *m = SetTopicResponse{} }
func (m *SetTopicResponse) String() string            { return proto.CompactTextString(m) }
func (*SetTopicResponse) ProtoMessage()               {}
func (*SetTopicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*Channel)(nil), "go.micro.srv.slack.Channel")
	proto.RegisterType((*ListRequest)(nil), "go.micro.srv.slack.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.srv.slack.ListResponse")
	proto.RegisterType((*HistoryRequest)(nil), "go.micro.srv.slack.HistoryRequest")
	proto.RegisterType((*HistoryResponse)(nil), "go.micro.srv.slack.HistoryResponse")
	proto.RegisterType((*InfoRequest)(nil), "go.micro.srv.slack.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "go.micro.srv.slack.InfoResponse")
	proto.RegisterType((*MarkRequest)(nil), "go.micro.srv.slack.MarkRequest")
	proto.RegisterType((*MarkResponse)(nil), "go.micro.srv.slack.MarkResponse")
	proto.RegisterType((*SetPurposeRequest)(nil), "go.micro.srv.slack.SetPurposeRequest")
	proto.RegisterType((*SetPurposeResponse)(nil), "go.micro.srv.slack.SetPurposeResponse")
	proto.RegisterType((*SetTopicRequest)(nil), "go.micro.srv.slack.SetTopicRequest")
	proto.RegisterType((*SetTopicResponse)(nil), "go.micro.srv.slack.SetTopicResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Channels service

type ChannelsClient interface {
	History(ctx context.Context, in *HistoryRequest, opts ...client.CallOption) (*HistoryResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	Mark(ctx context.Context, in *MarkRequest, opts ...client.CallOption) (*MarkResponse, error)
	SetPurpose(ctx context.Context, in *SetPurposeRequest, opts ...client.CallOption) (*SetPurposeResponse, error)
	SetTopic(ctx context.Context, in *SetTopicRequest, opts ...client.CallOption) (*SetTopicResponse, error)
}

type channelsClient struct {
	c           client.Client
	serviceName string
}

func NewChannelsClient(serviceName string, c client.Client) ChannelsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.slack"
	}
	return &channelsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *channelsClient) History(ctx context.Context, in *HistoryRequest, opts ...client.CallOption) (*HistoryResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Channels.History", in)
	out := new(HistoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelsClient) Info(ctx context.Context, in *InfoRequest, opts ...client.CallOption) (*InfoResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Channels.Info", in)
	out := new(InfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelsClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Channels.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelsClient) Mark(ctx context.Context, in *MarkRequest, opts ...client.CallOption) (*MarkResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Channels.Mark", in)
	out := new(MarkResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelsClient) SetPurpose(ctx context.Context, in *SetPurposeRequest, opts ...client.CallOption) (*SetPurposeResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Channels.SetPurpose", in)
	out := new(SetPurposeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelsClient) SetTopic(ctx context.Context, in *SetTopicRequest, opts ...client.CallOption) (*SetTopicResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Channels.SetTopic", in)
	out := new(SetTopicResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Channels service

type ChannelsHandler interface {
	History(context.Context, *HistoryRequest, *HistoryResponse) error
	Info(context.Context, *InfoRequest, *InfoResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
	Mark(context.Context, *MarkRequest, *MarkResponse) error
	SetPurpose(context.Context, *SetPurposeRequest, *SetPurposeResponse) error
	SetTopic(context.Context, *SetTopicRequest, *SetTopicResponse) error
}

func RegisterChannelsHandler(s server.Server, hdlr ChannelsHandler) {
	s.Handle(s.NewHandler(&Channels{hdlr}))
}

type Channels struct {
	ChannelsHandler
}

func (h *Channels) History(ctx context.Context, in *HistoryRequest, out *HistoryResponse) error {
	return h.ChannelsHandler.History(ctx, in, out)
}

func (h *Channels) Info(ctx context.Context, in *InfoRequest, out *InfoResponse) error {
	return h.ChannelsHandler.Info(ctx, in, out)
}

func (h *Channels) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.ChannelsHandler.List(ctx, in, out)
}

func (h *Channels) Mark(ctx context.Context, in *MarkRequest, out *MarkResponse) error {
	return h.ChannelsHandler.Mark(ctx, in, out)
}

func (h *Channels) SetPurpose(ctx context.Context, in *SetPurposeRequest, out *SetPurposeResponse) error {
	return h.ChannelsHandler.SetPurpose(ctx, in, out)
}

func (h *Channels) SetTopic(ctx context.Context, in *SetTopicRequest, out *SetTopicResponse) error {
	return h.ChannelsHandler.SetTopic(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0x75, 0xd3, 0xb8, 0x93, 0xb4, 0x69, 0x97, 0x1e, 0x96, 0x80, 0xa0, 0x72, 0xf9, 0x28,
	0xd0, 0x3a, 0xa2, 0x08, 0x89, 0x03, 0x07, 0x24, 0x2e, 0x20, 0xa8, 0x84, 0xa0, 0x52, 0xb9, 0xa0,
	0xc8, 0x75, 0x96, 0xc4, 0x8a, 0xed, 0x35, 0xbb, 0x76, 0x45, 0x0f, 0xfc, 0x6c, 0xce, 0x30, 0xbb,
	0xeb, 0x2f, 0x54, 0xbb, 0xbe, 0x65, 0xc7, 0x6f, 0xde, 0x7c, 0xbc, 0x37, 0x0a, 0xbc, 0x5e, 0x04,
	0xe9, 0x32, 0xbb, 0x70, 0x7d, 0x1e, 0x4d, 0xa3, 0xc0, 0x17, 0x7c, 0x2a, 0x43, 0xcf, 0x5f, 0x1d,
	0x4b, 0x71, 0x39, 0x4d, 0x04, 0x4f, 0xf9, 0xd4, 0x5f, 0x7a, 0x71, 0xcc, 0x42, 0x59, 0xfe, 0x70,
	0x75, 0x9c, 0x90, 0x05, 0x77, 0x75, 0x86, 0x8b, 0x58, 0x57, 0x67, 0x4d, 0x8e, 0xbb, 0xd9, 0x78,
	0x14, 0xf1, 0xd8, 0x50, 0x38, 0x7f, 0xd6, 0x60, 0xf0, 0xce, 0xb0, 0x12, 0x80, 0xb5, 0x60, 0x4e,
	0x7b, 0xfb, 0xbd, 0xc3, 0x4d, 0x32, 0x82, 0xf5, 0xd8, 0x8b, 0x18, 0x5d, 0xd3, 0xaf, 0x31, 0x0c,
	0x7c, 0xc1, 0xbc, 0x94, 0xcd, 0xa9, 0x85, 0x01, 0xab, 0x0c, 0x70, 0x41, 0xd7, 0x35, 0xe2, 0x36,
	0x0c, 0x03, 0x39, 0xf3, 0x84, 0xbf, 0x0c, 0x2e, 0x11, 0xd5, 0xc7, 0xa0, 0x4d, 0x76, 0x61, 0x13,
	0x83, 0x11, 0x8b, 0x2e, 0x98, 0xa0, 0x1b, 0x3a, 0x84, 0x45, 0x30, 0xb4, 0x60, 0x31, 0x13, 0x5e,
	0x48, 0x07, 0x3a, 0x86, 0xb9, 0x71, 0x16, 0xe5, 0x38, 0x49, 0x6d, 0x5d, 0xe1, 0x10, 0xfa, 0x29,
	0x4f, 0x02, 0x9f, 0x6e, 0xe2, 0x73, 0x78, 0x72, 0xc7, 0xbd, 0x3e, 0xab, 0x7b, 0xa6, 0x00, 0xe4,
	0x08, 0x06, 0x49, 0x26, 0x12, 0x2e, 0x19, 0x05, 0x8d, 0xbd, 0xdb, 0x84, 0xfd, 0x6c, 0x20, 0xaa,
	0xf3, 0xa2, 0xd0, 0x70, 0xdf, 0x32, 0x9d, 0x87, 0x38, 0x99, 0x4c, 0x67, 0x38, 0xd0, 0x9c, 0x8e,
	0xf4, 0x38, 0xcf, 0x61, 0xc3, 0x04, 0xe9, 0x56, 0x3b, 0xe5, 0x29, 0x93, 0xd2, 0x5b, 0x30, 0xb2,
	0x07, 0xa3, 0x2c, 0x56, 0xc9, 0x33, 0x9f, 0x67, 0x71, 0x4a, 0xb7, 0xf5, 0x00, 0xf7, 0x60, 0xaf,
	0x1e, 0x9d, 0xcd, 0x03, 0x99, 0x84, 0xde, 0x15, 0x1d, 0xab, 0xaf, 0xce, 0x13, 0x18, 0x7e, 0x0a,
	0x64, 0xfa, 0x85, 0xfd, 0xcc, 0xb0, 0x0a, 0xa1, 0xb0, 0xc3, 0x7e, 0xf9, 0x61, 0x36, 0x67, 0xd5,
	0x0e, 0x7b, 0x1a, 0xf8, 0x0d, 0x46, 0x06, 0x28, 0x13, 0x1e, 0x63, 0xff, 0x28, 0x12, 0x5f, 0xe9,
	0x6f, 0x36, 0xd9, 0x82, 0x3e, 0x13, 0x02, 0x35, 0x30, 0x2a, 0x1d, 0x83, 0x5d, 0x18, 0x04, 0x65,
	0xb2, 0xda, 0xda, 0xce, 0xe5, 0x76, 0x52, 0xd8, 0x7e, 0x8f, 0xcc, 0x5c, 0x5c, 0x15, 0x5d, 0x28,
	0x55, 0xcd, 0xc7, 0xdc, 0x05, 0xdb, 0xe5, 0x1a, 0x54, 0x85, 0x9e, 0x7a, 0xf3, 0x70, 0xae, 0xde,
	0x96, 0x7e, 0x2b, 0x81, 0x63, 0x6c, 0x5b, 0x62, 0xc3, 0xda, 0x08, 0x96, 0xea, 0xc9, 0x6c, 0xa1,
	0x5f, 0x18, 0xc5, 0x6c, 0x41, 0x6a, 0x03, 0x58, 0xce, 0x6f, 0x18, 0x97, 0x55, 0xbb, 0x47, 0xaa,
	0x1a, 0xb0, 0x8a, 0x11, 0x23, 0xb3, 0x75, 0x89, 0xf5, 0xac, 0x2e, 0x65, 0x76, 0xc0, 0x5e, 0x7a,
	0xe8, 0x40, 0x2e, 0x98, 0xb1, 0xa4, 0x73, 0x1f, 0x86, 0x1f, 0xe2, 0x1f, 0xbc, 0x6d, 0x62, 0xe7,
	0x1c, 0x46, 0xe6, 0x7b, 0x77, 0x6f, 0x47, 0x55, 0xae, 0xd5, 0x6e, 0x92, 0x62, 0xdb, 0xcf, 0x60,
	0x78, 0xea, 0x89, 0x55, 0xeb, 0xaa, 0xb1, 0x50, 0x2a, 0xcd, 0x9a, 0x9d, 0xa7, 0x30, 0x32, 0xd8,
	0xce, 0x26, 0x9c, 0x57, 0xb0, 0xfb, 0x95, 0xa5, 0xb9, 0xb9, 0x5b, 0xc9, 0xc7, 0xd5, 0x89, 0x98,
	0xb4, 0xb7, 0x40, 0xea, 0x69, 0xdd, 0xc3, 0xd6, 0x18, 0xb4, 0x12, 0xce, 0x0b, 0x18, 0x23, 0x83,
	0xbe, 0xc0, 0xd6, 0xb2, 0x5b, 0xc5, 0x0d, 0x9b, 0xa2, 0x6f, 0x60, 0xa7, 0x4a, 0xe9, 0x2e, 0x59,
	0x66, 0xeb, 0x82, 0x27, 0x7f, 0x2d, 0xb0, 0xf3, 0x65, 0x4a, 0x72, 0x06, 0x83, 0xdc, 0x45, 0xc4,
	0x69, 0xda, 0xfa, 0xff, 0xc6, 0x9e, 0x1c, 0xdc, 0x88, 0x31, 0xad, 0x38, 0xb7, 0xc8, 0x47, 0x58,
	0x57, 0xe2, 0x93, 0x07, 0x4d, 0xf0, 0x9a, 0x6d, 0x26, 0xfb, 0xed, 0x80, 0x3a, 0x99, 0x3a, 0xdc,
	0x66, 0xb2, 0xda, 0xed, 0x37, 0x93, 0xd5, 0x6f, 0xde, 0x90, 0x29, 0x47, 0x34, 0x93, 0xd5, 0x7c,
	0xd5, 0x4c, 0x56, 0x37, 0x13, 0x92, 0x7d, 0x07, 0xa8, 0xc4, 0x27, 0x8f, 0x9a, 0x32, 0xae, 0x79,
	0x6a, 0xf2, 0xb8, 0x0b, 0x56, 0xd2, 0x9f, 0x83, 0x5d, 0xc8, 0x4c, 0x0e, 0x5a, 0xb2, 0xea, 0xbe,
	0x99, 0x3c, 0xbc, 0x19, 0x54, 0x10, 0x5f, 0x6c, 0xe8, 0xbf, 0xac, 0x97, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x10, 0xf7, 0x25, 0x75, 0x31, 0x07, 0x00, 0x00,
}
