// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/slack-srv/proto/groups/groups.proto

/*
Package go_micro_srv_slack_group is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/slack-srv/proto/groups/groups.proto

It has these top-level messages:
	Group
	CloseRequest
	CloseResponse
	HistoryRequest
	HistoryResponse
	InfoRequest
	InfoResponse
	ListRequest
	ListResponse
	MarkRequest
	MarkResponse
	OpenRequest
	OpenResponse
	SetPurposeRequest
	SetPurposeResponse
	SetTopicRequest
	SetTopicResponse
*/
package go_micro_srv_slack_group

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_srv_slack "github.com/micro/slack-srv/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Group struct {
	Id                 string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name               string                      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	IsGroup            string                      `protobuf:"bytes,3,opt,name=is_group,json=isGroup" json:"is_group,omitempty"`
	Created            int64                       `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	Creator            int64                       `protobuf:"varint,5,opt,name=creator" json:"creator,omitempty"`
	IsArchived         bool                        `protobuf:"varint,6,opt,name=is_archived,json=isArchived" json:"is_archived,omitempty"`
	Members            []string                    `protobuf:"bytes,7,rep,name=members" json:"members,omitempty"`
	Topic              *go_micro_srv_slack.Topic   `protobuf:"bytes,8,opt,name=topic" json:"topic,omitempty"`
	Purpose            *go_micro_srv_slack.Purpose `protobuf:"bytes,9,opt,name=purpose" json:"purpose,omitempty"`
	LatestRead         string                      `protobuf:"bytes,10,opt,name=latest_read,json=latestRead" json:"latest_read,omitempty"`
	Latest             *go_micro_srv_slack.Message `protobuf:"bytes,11,opt,name=latest" json:"latest,omitempty"`
	UnreadCount        int64                       `protobuf:"varint,12,opt,name=unread_count,json=unreadCount" json:"unread_count,omitempty"`
	UnreadCountDisplay int64                       `protobuf:"varint,13,opt,name=unread_count_display,json=unreadCountDisplay" json:"unread_count_display,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetIsGroup() string {
	if m != nil {
		return m.IsGroup
	}
	return ""
}

func (m *Group) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Group) GetCreator() int64 {
	if m != nil {
		return m.Creator
	}
	return 0
}

func (m *Group) GetIsArchived() bool {
	if m != nil {
		return m.IsArchived
	}
	return false
}

func (m *Group) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Group) GetTopic() *go_micro_srv_slack.Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Group) GetPurpose() *go_micro_srv_slack.Purpose {
	if m != nil {
		return m.Purpose
	}
	return nil
}

func (m *Group) GetLatestRead() string {
	if m != nil {
		return m.LatestRead
	}
	return ""
}

func (m *Group) GetLatest() *go_micro_srv_slack.Message {
	if m != nil {
		return m.Latest
	}
	return nil
}

func (m *Group) GetUnreadCount() int64 {
	if m != nil {
		return m.UnreadCount
	}
	return 0
}

func (m *Group) GetUnreadCountDisplay() int64 {
	if m != nil {
		return m.UnreadCountDisplay
	}
	return 0
}

type CloseRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *CloseRequest) Reset()                    { *m = CloseRequest{} }
func (m *CloseRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()               {}
func (*CloseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CloseRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type CloseResponse struct {
	Ok            bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error         string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	NoOp          bool   `protobuf:"varint,3,opt,name=no_op,json=noOp" json:"no_op,omitempty"`
	AlreadyClosed bool   `protobuf:"varint,4,opt,name=already_closed,json=alreadyClosed" json:"already_closed,omitempty"`
}

func (m *CloseResponse) Reset()                    { *m = CloseResponse{} }
func (m *CloseResponse) String() string            { return proto.CompactTextString(m) }
func (*CloseResponse) ProtoMessage()               {}
func (*CloseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CloseResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *CloseResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CloseResponse) GetNoOp() bool {
	if m != nil {
		return m.NoOp
	}
	return false
}

func (m *CloseResponse) GetAlreadyClosed() bool {
	if m != nil {
		return m.AlreadyClosed
	}
	return false
}

type HistoryRequest struct {
	Channel   string  `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Latest    float64 `protobuf:"fixed64,2,opt,name=latest" json:"latest,omitempty"`
	Oldest    float64 `protobuf:"fixed64,3,opt,name=oldest" json:"oldest,omitempty"`
	Inclusive int64   `protobuf:"varint,4,opt,name=inclusive" json:"inclusive,omitempty"`
	Count     int64   `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	Unreads   int64   `protobuf:"varint,6,opt,name=unreads" json:"unreads,omitempty"`
}

func (m *HistoryRequest) Reset()                    { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string            { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()               {}
func (*HistoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HistoryRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *HistoryRequest) GetLatest() float64 {
	if m != nil {
		return m.Latest
	}
	return 0
}

func (m *HistoryRequest) GetOldest() float64 {
	if m != nil {
		return m.Oldest
	}
	return 0
}

func (m *HistoryRequest) GetInclusive() int64 {
	if m != nil {
		return m.Inclusive
	}
	return 0
}

func (m *HistoryRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *HistoryRequest) GetUnreads() int64 {
	if m != nil {
		return m.Unreads
	}
	return 0
}

type HistoryResponse struct {
	Ok       bool                          `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error    string                        `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Latest   string                        `protobuf:"bytes,3,opt,name=latest" json:"latest,omitempty"`
	Messages []*go_micro_srv_slack.Message `protobuf:"bytes,4,rep,name=messages" json:"messages,omitempty"`
	HasMore  bool                          `protobuf:"varint,5,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
}

func (m *HistoryResponse) Reset()                    { *m = HistoryResponse{} }
func (m *HistoryResponse) String() string            { return proto.CompactTextString(m) }
func (*HistoryResponse) ProtoMessage()               {}
func (*HistoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HistoryResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *HistoryResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *HistoryResponse) GetLatest() string {
	if m != nil {
		return m.Latest
	}
	return ""
}

func (m *HistoryResponse) GetMessages() []*go_micro_srv_slack.Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *HistoryResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type InfoRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InfoRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type InfoResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Group *Group `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InfoResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *InfoResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *InfoResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type ListRequest struct {
	ExcludeArchived int64 `protobuf:"varint,1,opt,name=exclude_archived,json=excludeArchived" json:"exclude_archived,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListRequest) GetExcludeArchived() int64 {
	if m != nil {
		return m.ExcludeArchived
	}
	return 0
}

type ListResponse struct {
	Ok     bool     `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error  string   `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Groups []*Group `protobuf:"bytes,3,rep,name=groups" json:"groups,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *ListResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type MarkRequest struct {
	Channel string  `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Ts      float64 `protobuf:"fixed64,2,opt,name=ts" json:"ts,omitempty"`
}

func (m *MarkRequest) Reset()                    { *m = MarkRequest{} }
func (m *MarkRequest) String() string            { return proto.CompactTextString(m) }
func (*MarkRequest) ProtoMessage()               {}
func (*MarkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MarkRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *MarkRequest) GetTs() float64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type MarkResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *MarkResponse) Reset()                    { *m = MarkResponse{} }
func (m *MarkResponse) String() string            { return proto.CompactTextString(m) }
func (*MarkResponse) ProtoMessage()               {}
func (*MarkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MarkResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *MarkResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type OpenRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
}

func (m *OpenRequest) Reset()                    { *m = OpenRequest{} }
func (m *OpenRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()               {}
func (*OpenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *OpenRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type OpenResponse struct {
	Ok          bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error       string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	NoOp        bool   `protobuf:"varint,3,opt,name=no_op,json=noOp" json:"no_op,omitempty"`
	AlreadyOpen bool   `protobuf:"varint,4,opt,name=already_open,json=alreadyOpen" json:"already_open,omitempty"`
}

func (m *OpenResponse) Reset()                    { *m = OpenResponse{} }
func (m *OpenResponse) String() string            { return proto.CompactTextString(m) }
func (*OpenResponse) ProtoMessage()               {}
func (*OpenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *OpenResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *OpenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *OpenResponse) GetNoOp() bool {
	if m != nil {
		return m.NoOp
	}
	return false
}

func (m *OpenResponse) GetAlreadyOpen() bool {
	if m != nil {
		return m.AlreadyOpen
	}
	return false
}

type SetPurposeRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Purpose string `protobuf:"bytes,2,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *SetPurposeRequest) Reset()                    { *m = SetPurposeRequest{} }
func (m *SetPurposeRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPurposeRequest) ProtoMessage()               {}
func (*SetPurposeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SetPurposeRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SetPurposeRequest) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

type SetPurposeResponse struct {
	Ok      bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Purpose string `protobuf:"bytes,3,opt,name=purpose" json:"purpose,omitempty"`
}

func (m *SetPurposeResponse) Reset()                    { *m = SetPurposeResponse{} }
func (m *SetPurposeResponse) String() string            { return proto.CompactTextString(m) }
func (*SetPurposeResponse) ProtoMessage()               {}
func (*SetPurposeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SetPurposeResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SetPurposeResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SetPurposeResponse) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

type SetTopicRequest struct {
	Channel string `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	Topic   string `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
}

func (m *SetTopicRequest) Reset()                    { *m = SetTopicRequest{} }
func (m *SetTopicRequest) String() string            { return proto.CompactTextString(m) }
func (*SetTopicRequest) ProtoMessage()               {}
func (*SetTopicRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SetTopicRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SetTopicRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type SetTopicResponse struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Topic string `protobuf:"bytes,3,opt,name=topic" json:"topic,omitempty"`
}

func (m *SetTopicResponse) Reset()                    { *m = SetTopicResponse{} }
func (m *SetTopicResponse) String() string            { return proto.CompactTextString(m) }
func (*SetTopicResponse) ProtoMessage()               {}
func (*SetTopicResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SetTopicResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *SetTopicResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SetTopicResponse) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*Group)(nil), "go.micro.srv.slack.group.Group")
	proto.RegisterType((*CloseRequest)(nil), "go.micro.srv.slack.group.CloseRequest")
	proto.RegisterType((*CloseResponse)(nil), "go.micro.srv.slack.group.CloseResponse")
	proto.RegisterType((*HistoryRequest)(nil), "go.micro.srv.slack.group.HistoryRequest")
	proto.RegisterType((*HistoryResponse)(nil), "go.micro.srv.slack.group.HistoryResponse")
	proto.RegisterType((*InfoRequest)(nil), "go.micro.srv.slack.group.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "go.micro.srv.slack.group.InfoResponse")
	proto.RegisterType((*ListRequest)(nil), "go.micro.srv.slack.group.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.srv.slack.group.ListResponse")
	proto.RegisterType((*MarkRequest)(nil), "go.micro.srv.slack.group.MarkRequest")
	proto.RegisterType((*MarkResponse)(nil), "go.micro.srv.slack.group.MarkResponse")
	proto.RegisterType((*OpenRequest)(nil), "go.micro.srv.slack.group.OpenRequest")
	proto.RegisterType((*OpenResponse)(nil), "go.micro.srv.slack.group.OpenResponse")
	proto.RegisterType((*SetPurposeRequest)(nil), "go.micro.srv.slack.group.SetPurposeRequest")
	proto.RegisterType((*SetPurposeResponse)(nil), "go.micro.srv.slack.group.SetPurposeResponse")
	proto.RegisterType((*SetTopicRequest)(nil), "go.micro.srv.slack.group.SetTopicRequest")
	proto.RegisterType((*SetTopicResponse)(nil), "go.micro.srv.slack.group.SetTopicResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Groups service

type GroupsClient interface {
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Mark(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*MarkResponse, error)
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	SetPurpose(ctx context.Context, in *SetPurposeRequest, opts ...grpc.CallOption) (*SetPurposeResponse, error)
	SetTopic(ctx context.Context, in *SetTopicRequest, opts ...grpc.CallOption) (*SetTopicResponse, error)
}

type groupsClient struct {
	cc *grpc.ClientConn
}

func NewGroupsClient(cc *grpc.ClientConn) GroupsClient {
	return &groupsClient{cc}
}

func (c *groupsClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.slack.group.Groups/Close", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	out := new(HistoryResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.slack.group.Groups/History", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.slack.group.Groups/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.slack.group.Groups/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Mark(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*MarkResponse, error) {
	out := new(MarkResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.slack.group.Groups/Mark", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	out := new(OpenResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.slack.group.Groups/Open", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) SetPurpose(ctx context.Context, in *SetPurposeRequest, opts ...grpc.CallOption) (*SetPurposeResponse, error) {
	out := new(SetPurposeResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.slack.group.Groups/SetPurpose", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupsClient) SetTopic(ctx context.Context, in *SetTopicRequest, opts ...grpc.CallOption) (*SetTopicResponse, error) {
	out := new(SetTopicResponse)
	err := grpc.Invoke(ctx, "/go.micro.srv.slack.group.Groups/SetTopic", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Groups service

type GroupsServer interface {
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	History(context.Context, *HistoryRequest) (*HistoryResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Mark(context.Context, *MarkRequest) (*MarkResponse, error)
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	SetPurpose(context.Context, *SetPurposeRequest) (*SetPurposeResponse, error)
	SetTopic(context.Context, *SetTopicRequest) (*SetTopicResponse, error)
}

func RegisterGroupsServer(s *grpc.Server, srv GroupsServer) {
	s.RegisterService(&_Groups_serviceDesc, srv)
}

func _Groups_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.slack.group.Groups/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.slack.group.Groups/History",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).History(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.slack.group.Groups/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.slack.group.Groups/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Mark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Mark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.slack.group.Groups/Mark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Mark(ctx, req.(*MarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.slack.group.Groups/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_SetPurpose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPurposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).SetPurpose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.slack.group.Groups/SetPurpose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).SetPurpose(ctx, req.(*SetPurposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Groups_SetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupsServer).SetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.slack.group.Groups/SetTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupsServer).SetTopic(ctx, req.(*SetTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Groups_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.slack.group.Groups",
	HandlerType: (*GroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Close",
			Handler:    _Groups_Close_Handler,
		},
		{
			MethodName: "History",
			Handler:    _Groups_History_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Groups_Info_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Groups_List_Handler,
		},
		{
			MethodName: "Mark",
			Handler:    _Groups_Mark_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _Groups_Open_Handler,
		},
		{
			MethodName: "SetPurpose",
			Handler:    _Groups_SetPurpose_Handler,
		},
		{
			MethodName: "SetTopic",
			Handler:    _Groups_SetTopic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/micro/slack-srv/proto/groups/groups.proto",
}

func init() {
	proto.RegisterFile("github.com/micro/slack-srv/proto/groups/groups.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 883 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x0e, 0x45, 0xfd, 0xd0, 0x43, 0xd9, 0x4e, 0xb7, 0x46, 0xb0, 0x51, 0x0b, 0x44, 0x21, 0x90,
	0x44, 0x6e, 0x1b, 0xaa, 0x70, 0x12, 0xb8, 0xd7, 0x20, 0x05, 0xd2, 0x02, 0x75, 0x53, 0x30, 0x01,
	0x0a, 0xf4, 0xc2, 0xd2, 0xe4, 0xd6, 0x5a, 0x88, 0xe4, 0x32, 0xbb, 0xa4, 0x51, 0x3f, 0x4f, 0x2f,
	0x7d, 0x94, 0x3e, 0x53, 0x4f, 0xc5, 0xfe, 0x90, 0xda, 0xa0, 0x91, 0x68, 0x21, 0x27, 0x69, 0x86,
	0xdf, 0x7c, 0x33, 0x9c, 0x99, 0x6f, 0x24, 0x78, 0x7e, 0x45, 0xeb, 0x55, 0x73, 0x19, 0xa6, 0xac,
	0x58, 0x16, 0x34, 0xe5, 0x6c, 0x29, 0xf2, 0x24, 0x5d, 0x3f, 0x15, 0xfc, 0x7a, 0x59, 0x71, 0x56,
	0xb3, 0xe5, 0x15, 0x67, 0x4d, 0x25, 0xcc, 0x47, 0xa8, 0x7c, 0x08, 0x5f, 0xb1, 0x50, 0xa1, 0x43,
	0xc1, 0xaf, 0x43, 0x15, 0x11, 0x2a, 0xc0, 0xec, 0x69, 0x2f, 0x5f, 0xca, 0x8a, 0x82, 0x95, 0x9a,
	0x28, 0xf8, 0xc7, 0x85, 0xd1, 0x6b, 0x19, 0x88, 0x8e, 0x60, 0x40, 0x33, 0xec, 0xcc, 0x9d, 0xc5,
	0x41, 0x34, 0xa0, 0x19, 0x42, 0x30, 0x2c, 0x93, 0x82, 0xe0, 0x81, 0xf2, 0xa8, 0xef, 0xe8, 0x3e,
	0x78, 0x54, 0xc4, 0x2a, 0x11, 0x76, 0x95, 0x7f, 0x42, 0x85, 0x0e, 0xc7, 0x30, 0x49, 0x39, 0x49,
	0x6a, 0x92, 0xe1, 0xe1, 0xdc, 0x59, 0xb8, 0x51, 0x6b, 0x76, 0x4f, 0x18, 0xc7, 0x23, 0xeb, 0x09,
	0xe3, 0xe8, 0x01, 0xf8, 0x54, 0xc4, 0x09, 0x4f, 0x57, 0xf4, 0x9a, 0x64, 0x78, 0x3c, 0x77, 0x16,
	0x5e, 0x04, 0x54, 0xbc, 0x34, 0x1e, 0x19, 0x5a, 0x90, 0xe2, 0x92, 0x70, 0x81, 0x27, 0x73, 0x57,
	0xa6, 0x33, 0x26, 0x5a, 0xc2, 0xa8, 0x66, 0x15, 0x4d, 0xb1, 0x37, 0x77, 0x16, 0xfe, 0xd9, 0xfd,
	0xf0, 0x23, 0x0d, 0x79, 0x27, 0x01, 0x91, 0xc6, 0xa1, 0x17, 0x30, 0xa9, 0x1a, 0x5e, 0x31, 0x41,
	0xf0, 0x81, 0x0a, 0xf9, 0xe2, 0x63, 0x21, 0xbf, 0x68, 0x48, 0xd4, 0x62, 0x65, 0x89, 0x79, 0x52,
	0x13, 0x51, 0xc7, 0x9c, 0x24, 0x19, 0x06, 0xf5, 0xd2, 0xa0, 0x5d, 0x11, 0x49, 0x32, 0xf4, 0x0c,
	0xc6, 0xda, 0xc2, 0xfe, 0x76, 0xda, 0x0b, 0x22, 0x44, 0x72, 0x45, 0x22, 0x03, 0x45, 0x0f, 0x61,
	0xda, 0x94, 0x92, 0x30, 0x4e, 0x59, 0x53, 0xd6, 0x78, 0xaa, 0xfa, 0xe2, 0x6b, 0xdf, 0x2b, 0xe9,
	0x42, 0xdf, 0xc2, 0x89, 0x0d, 0x89, 0x33, 0x2a, 0xaa, 0x3c, 0xb9, 0xc1, 0x87, 0x0a, 0x8a, 0x2c,
	0xe8, 0xf7, 0xfa, 0x49, 0xb0, 0x80, 0xe9, 0xab, 0x5c, 0x16, 0x4f, 0xde, 0x37, 0x32, 0x89, 0xec,
	0xfb, 0x2a, 0x29, 0x4b, 0x92, 0x9b, 0xa9, 0xb6, 0x66, 0xf0, 0x1e, 0x0e, 0x0d, 0x52, 0x54, 0xac,
	0x14, 0x44, 0xce, 0x9e, 0xad, 0x15, 0xca, 0x8b, 0x06, 0x6c, 0x8d, 0x4e, 0x60, 0x44, 0x38, 0x67,
	0xdc, 0x0c, 0x5f, 0x1b, 0xe8, 0x73, 0x18, 0x95, 0x2c, 0x66, 0x7a, 0xf4, 0x5e, 0x34, 0x2c, 0xd9,
	0x9b, 0x0a, 0x3d, 0x82, 0xa3, 0x24, 0x97, 0xb5, 0xdc, 0xc4, 0xa9, 0xe4, 0xd4, 0xe3, 0xf7, 0xa2,
	0x43, 0xe3, 0x55, 0x89, 0xb2, 0xe0, 0x6f, 0x07, 0x8e, 0x7e, 0xa0, 0xa2, 0x66, 0xfc, 0xa6, 0xb7,
	0x3e, 0x74, 0xaf, 0xeb, 0xa9, 0xcc, 0xef, 0x74, 0x6d, 0xbb, 0x07, 0x63, 0x96, 0x67, 0xd2, 0xef,
	0x6a, 0xbf, 0xb6, 0xd0, 0x97, 0x70, 0x40, 0xcb, 0x34, 0x6f, 0x04, 0xbd, 0x26, 0x66, 0xfb, 0x36,
	0x0e, 0xf9, 0x32, 0xba, 0xcb, 0x7a, 0xfb, 0xb4, 0x21, 0xb3, 0xeb, 0x1e, 0x0a, 0xb5, 0x77, 0x6e,
	0xd4, 0x9a, 0xc1, 0x5f, 0x0e, 0x1c, 0x77, 0xa5, 0xee, 0xd5, 0xa0, 0x4d, 0xdd, 0x5a, 0x1c, 0x6d,
	0xdd, 0xe7, 0xe0, 0x15, 0x7a, 0x03, 0x04, 0x1e, 0xce, 0xdd, 0xbe, 0x2d, 0xe9, 0xc0, 0x52, 0x6f,
	0xab, 0x44, 0xc4, 0x05, 0xe3, 0x44, 0x55, 0xef, 0x45, 0x93, 0x55, 0x22, 0x2e, 0x18, 0x27, 0xc1,
	0x13, 0xf0, 0x7f, 0x2c, 0xff, 0x60, 0xfd, 0xc3, 0x5e, 0xc3, 0x54, 0x03, 0xf7, 0x7a, 0x95, 0x17,
	0x30, 0xda, 0xc8, 0xdc, 0x3f, 0x7b, 0x10, 0x6e, 0x3b, 0x38, 0xa1, 0x92, 0x7f, 0xa4, 0xd1, 0xc1,
	0x77, 0xe0, 0xff, 0x44, 0xa5, 0x32, 0x74, 0x55, 0xa7, 0x70, 0x97, 0xfc, 0x99, 0xe6, 0x4d, 0x46,
	0x36, 0x2a, 0x77, 0x54, 0xb7, 0x8f, 0x8d, 0xbf, 0x95, 0x7a, 0x50, 0xc0, 0x54, 0x47, 0xee, 0x55,
	0xe6, 0x39, 0x8c, 0xf5, 0x5d, 0xc4, 0xae, 0xea, 0x6b, 0x6f, 0x9d, 0x06, 0x1e, 0x9c, 0x83, 0x7f,
	0x91, 0xf0, 0x75, 0xff, 0x2e, 0x1e, 0xc1, 0xa0, 0x16, 0x66, 0x0f, 0x07, 0xb5, 0x08, 0x9e, 0xc3,
	0x54, 0x07, 0xee, 0x53, 0xa7, 0x9c, 0xd6, 0x9b, 0x8a, 0x94, 0xfd, 0xd3, 0xca, 0x61, 0xaa, 0x81,
	0x9f, 0xae, 0xcc, 0x87, 0x30, 0x6d, 0x95, 0xc9, 0x2a, 0x52, 0x1a, 0x5d, 0xfa, 0xc6, 0x27, 0xb3,
	0x04, 0xaf, 0xe1, 0xb3, 0xb7, 0xa4, 0x6e, 0x8f, 0x5e, 0x6f, 0x2f, 0xf0, 0xe6, 0x86, 0xea, 0xf4,
	0xad, 0x19, 0xbc, 0x03, 0x64, 0x13, 0xed, 0x55, 0xbc, 0xc5, 0xea, 0x7e, 0xc8, 0xfa, 0x12, 0x8e,
	0xdf, 0x92, 0x5a, 0x9f, 0xf1, 0xde, 0xe2, 0x4e, 0xda, 0x5f, 0x04, 0x43, 0xae, 0x8c, 0xe0, 0x67,
	0xb8, 0xbb, 0xa1, 0xd8, 0xab, 0xac, 0x8e, 0xcf, 0xb5, 0xf8, 0xce, 0xfe, 0x1d, 0xc1, 0x58, 0x6d,
	0x92, 0x40, 0xbf, 0xc1, 0x48, 0x1d, 0x37, 0xf4, 0x78, 0xfb, 0xd2, 0xd9, 0x07, 0x79, 0xf6, 0xa4,
	0x17, 0xa7, 0x0b, 0x0c, 0xee, 0xa0, 0xdf, 0x61, 0x62, 0x4e, 0x10, 0x5a, 0x6c, 0x8f, 0xfa, 0xf0,
	0xa0, 0xce, 0x4e, 0x6f, 0x81, 0xec, 0x32, 0xfc, 0x0a, 0x43, 0x79, 0x16, 0xd0, 0xa3, 0xed, 0x41,
	0xd6, 0x7d, 0x99, 0x3d, 0xee, 0x83, 0xd9, 0xc4, 0x52, 0xc8, 0xbb, 0x88, 0xad, 0x13, 0xb1, 0x8b,
	0xd8, 0xbe, 0x07, 0x9a, 0x58, 0x2a, 0x6f, 0x17, 0xb1, 0x25, 0xe9, 0x5d, 0xc4, 0xb6, 0x80, 0x35,
	0xb1, 0x54, 0xc3, 0x2e, 0x62, 0x4b, 0xbc, 0xbb, 0x88, 0x6d, 0xe9, 0x06, 0x77, 0x10, 0x05, 0xd8,
	0xa8, 0x02, 0x7d, 0xbd, 0x3d, 0xee, 0x7f, 0x22, 0x9c, 0x7d, 0x73, 0x3b, 0x70, 0x97, 0x2a, 0x05,
	0xaf, 0xdd, 0x73, 0x74, 0xba, 0x33, 0xd6, 0x96, 0xd3, 0xec, 0xab, 0xdb, 0x40, 0xdb, 0x24, 0x97,
	0x63, 0xf5, 0x9f, 0xf1, 0xd9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xa8, 0x90, 0x63, 0xb4,
	0x0a, 0x00, 0x00,
}
